name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ naher555nnnn }}" | docker login -u "${{ naherin }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t ${{ naherin }}/flask-app:latest .

    - name: Push image to Docker Hub
      run: docker push ${{ naherin }}/flask-app:latest
